# Generated by Django 4.0.1 on 2022-02-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandsManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('bands_type', models.CharField(choices=[('R', 'Rap'), ('Ro', 'Rock'), ('F', 'Falk'), ('O', 'Other')], max_length=20)),
                ('band', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bands.band')),
            ],
        ),
    ]
