# Generated by Django 4.0.1 on 2022-02-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_bandsmanage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandsmanage',
            name='description',
            field=models.TextField(default='description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bandsmanage',
            name='bands_type',
            field=models.CharField(choices=[('Rap', 'Rap'), ('Rock', 'Rock'), ('Falk', 'Falk'), ('Other', 'Other')], max_length=20),
        ),
    ]
