# Generated by Django 4.0.1 on 2022-02-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_bandsmanage_description_alter_bandsmanage_bands_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BandsManage',
            new_name='BandsAdd',
        ),
    ]
